[app]
addr = "0.0.0.0:8080"
log_level = "debug"
prometheus_port = 9100
enable_signature = false
api_key = "iobscan-explorer-backend"

[mongodb]
url = "mongodb://wcchain:wcchainPassword@192.168.150.40:27017/?authSource=iobscan_wcchain"
database = "iobscan_wcchain"

[lcd]
backend = "http://47.100.192.234:1317"
bond_tokens_url = "/cosmos/staking/v1beta1/pool"
total_supply_url = "/cosmos/bank/v1beta1/supply"
community_pool_url = "/cosmos/distribution/v1beta1/community_pool"

[task]
cron_jobs = "ex_sync_denom,ex_sync_nft"