[app]
addr = "0.0.0.0:8080"
log_level = "debug"
prometheus_port = 9100
enable_signature = false
api_key = "iobscan-explorer-backend"

[mongodb]
host = "192.168.150.40"
port = 27017
username = "wcchain"
password = "wcchainPassword"
database = "iobscan_wcchain"

[lcd]
backend = "http://47.100.192.234:1317"
bond_tokens_url = "/cosmos/staking/v1beta1/pool"
total_supply_url = "/cosmos/bank/v1beta1/supply"
community_pool_url = "/cosmos/distribution/v1beta1/community_pool"

[irishub]
rpc_addr = "http://192.168.0.129:26657"
grpc_addr = "192.168.0.129:9090"
chain_id = "irishub-qa"
